// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: example.sql

package sqlc

import (
	"context"
)

const getExampleByID = `-- name: GetExampleByID :one
SELECT id FROM example
WHERE id = ?
`

func (q *Queries) GetExampleByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getExampleByID, id)
	err := row.Scan(&id)
	return id, err
}
